Repository Attendize/Attendize, pull requests merged in 2020-04, with the labels that each got.

#769 Event create UI form error handling
  public/assets/javascript/app.js
  public/assets/javascript/backend.js
  resources/views/ManageOrganiser/Modals/CreateEvent.blade.php
Labels: bug, enhancement, next

#770 New markdown parser
  composer.json
  composer.lock
  config/app.php
  resources/views/Public/ViewEvent/Layouts/EventPage.blade.php
  resources/views/Public/ViewEvent/Partials/EventDescriptionSection.blade.php
  resources/views/Public/ViewEvent/Partials/EventViewOrderSection.blade.php
  resources/views/Public/ViewEvent/Partials/OfflinePayments.blade.php
Labels: next, security

#774 Offline Payments Copy Fixes
  resources/views/ManageEvent/Modals/CancelAttendee.blade.php
  resources/views/ManageEvent/Modals/CancelOrder.blade.php
  routes/web.php
Labels: bug, next, quick fix

#775 General regression fixes after laravel 6 upgrade
  app/Exports/AttendeesExport.php
  app/Exports/OrdersExport.php
  app/Http/Controllers/EventAttendeesController.php
  app/Http/Controllers/EventOrdersController.php
  app/Imports/AttendeesImport.php
  app/Models/Order.php
  app/Models/OrderItem.php
  config/app.php
  resources/lang/en/Attendee.php
  resources/lang/en/Ticket.php
  resources/views/ManageOrganiser/Customize.blade.php
Labels: bug, next

#629 Do not escape html for post order message
  resources/views/Public/ViewEvent/Partials/EventViewOrderSection.blade.php
Labels: bug

#743 Fix XSS and 500 error if version check fails
  app/Attendize/Utils.php
  app/Http/Controllers/ManageAccountController.php
  resources/views/ManageAccount/Modals/EditAccount.blade.php
  tests/Feature/Utils/UtilsTest.php
Labels: bug
